create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  bio text not null default '',
  profile_image text not null default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null default '자유',
  author_id uuid references public.profiles(id) on delete set null,
  views integer not null default 0,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 500),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.post_reactions (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_views (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create or replace view public.post_list as
select p.id, p.title, p.content, p.category, p.author_id, p.views, p.is_hidden, p.created_at,
  coalesce(pr.name, '알 수 없음') as author,
  (select count(*) from public.post_reactions r where r.post_id = p.id and r.reaction = 'like')::integer as likes,
  (select count(*) from public.post_reactions r where r.post_id = p.id and r.reaction = 'dislike')::integer as dislikes,
  (select count(*) from public.comments c where c.post_id = p.id and c.is_hidden = false)::integer as comment_count
from public.posts p left join public.profiles pr on pr.id = p.author_id;

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_reactions enable row level security;
alter table public.post_views enable row level security;
