create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references public.profiles(id) on delete set null,
  target_type text not null check (target_type in ('post', 'comment')),
  target_id bigint not null,
  reason text not null,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

insert into public.site_settings (key, value) values
  ('site_name', 'Community'),
  ('site_description', '함께 나누고 성장하는 커뮤니티'),
  ('maintenance_mode', 'false')
on conflict (key) do nothing;

alter table public.reports enable row level security;
alter table public.site_settings enable row level security;
