-- Dedicated administrator notices, separate from community posts.
create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 200),
  content text not null check (char_length(trim(content)) between 1 and 10000),
  is_published boolean not null default true,
  show_as_modal boolean not null default true,
  published_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notices_published_at_idx on public.notices (is_published, published_at desc);
create index if not exists inquiries_user_created_at_idx on public.inquiries (user_id, created_at desc);
create index if not exists inquiries_status_created_at_idx on public.inquiries (status, created_at desc);
create index if not exists reports_status_created_at_idx on public.reports (status, created_at desc);
create index if not exists reports_target_idx on public.reports (target_type, target_id);

alter table public.notices enable row level security;
