import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { authStorage } from './authStorage.js'
import { apiFetch } from './api.js'

const headers = () => ({ Authorization: `Bearer ${authStorage.getItem('adminToken')}` })
const date = (value) => value ? new Date(value).toLocaleDateString('ko-KR') : '-'
const emptyMetrics = { posts: 0, comments: 0, users: 0, views: 0 }

export default function AdminPosts() {
  const [tab, setTab] = useState('dashboard'); const [dashboard, setDashboard] = useState({ metrics: emptyMetrics, recentPosts: [], recentComments: [] }); const [reports, setReports] = useState([]); const [inquiries, setInquiries] = useState([]); const [notice, setNotice] = useState({ title: '', content: '' }); const [error, setError] = useState('')
  const load = async () => { try { const [stats, reportData, inquiryData] = await Promise.all([apiFetch('/admin/dashboard', { headers: headers() }), apiFetch('/admin/reports', { headers: headers() }), apiFetch('/admin/inquiries', { headers: headers() })]); setDashboard(stats); setReports(reportData); setInquiries(inquiryData) } catch (caught) { setError(caught.message) } }
  useEffect(() => { load() }, [])
  const createNotice = async (event) => { event.preventDefault(); try { await apiFetch('/admin/posts', { method: 'POST', headers: { ...headers(), 'Content-Type': 'application/json' }, body: JSON.stringify({ ...notice, category: '공지' }) }); setNotice({ title: '', content: '' }); setError('공지사항을 등록했습니다.'); await load() } catch (caught) { setError(caught.message) } }
  const updateReport = async (id, status) => { try { await apiFetch(`/admin/reports/${id}`, { method: 'PATCH', headers: { ...headers(), 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); await load() } catch (caught) { setError(caught.message) } }
  const answerInquiry = async (id, answer, status = 'answered') => { try { await apiFetch(`/admin/inquiries/${id}`, { method: 'PATCH', headers: { ...headers(), 'Content-Type': 'application/json' }, body: JSON.stringify({ answer, status }) }); await load() } catch (caught) { setError(caught.message) } }
  const logout = () => { authStorage.removeItem('adminToken'); window.location.href = '/admin/login' }
  return <section className="admin-dashboard"><div className="admin-topbar"><div><p className="admin-kicker">ADMIN CENTER</p><h1>관리자 센터</h1></div><div className="admin-dashboard-actions"><Link to="/" className="admin-home">사이트 보기</Link><button className="admin-logout-top" onClick={logout}>로그아웃</button></div></div><div className="admin-tabs">{[['dashboard','대시보드'],['notices','공지사항'],['inquiries','문의하기'],['reports','신고하기']].map(([id, label]) => <button key={id} className={tab === id ? 'selected' : ''} onClick={() => setTab(id)}>{label}{id === 'reports' && <b>{reports.filter((item) => item.status === 'pending').length}</b>}</button>)}</div>{error && <p className="admin-posts-message">{error}</p>}{tab === 'dashboard' && <><div className="dashboard-metrics"><div><small>게시글</small><strong>{dashboard.metrics?.posts || 0}</strong></div><div><small>댓글</small><strong>{dashboard.metrics?.comments || 0}</strong></div><div><small>회원</small><strong>{dashboard.metrics?.users || 0}</strong></div><div><small>총 조회수</small><strong>{dashboard.metrics?.views || 0}</strong></div></div><div className="dashboard-grid"><section className="dashboard-panel"><h2>최근 게시글</h2>{dashboard.recentPosts?.map((post) => <Link className="dashboard-post" to={`/board/${post.id}`} key={post.id}><div><strong>{post.title}</strong><small>{post.author} · {date(post.created_at)}</small></div></Link>)}</section><section className="dashboard-panel"><h2>최근 댓글</h2>{dashboard.recentComments?.map((item) => <div className="dashboard-comment" key={item.id}><strong>{item.author}</strong><p>{item.content}</p></div>)}</section></div></>}{tab === 'notices' && <form className="dashboard-panel admin-settings" onSubmit={createNotice}><h2>공지사항 등록</h2><label>제목<input required value={notice.title} onChange={(event) => setNotice({ ...notice, title: event.target.value })} /></label><label>내용<textarea required rows="8" value={notice.content} onChange={(event) => setNotice({ ...notice, content: event.target.value })} /></label><button className="admin-button">공지 등록</button></form>}{tab === 'inquiries' && <section className="dashboard-panel"><h2>문의 관리</h2>{inquiries.length ? inquiries.map((item) => <InquiryRow key={item.id} item={item} onSave={answerInquiry} />) : <p className="dashboard-empty">접수된 문의가 없습니다.</p>}</section>}{tab === 'reports' && <section className="dashboard-panel"><h2>신고 관리</h2>{reports.length ? reports.map((item) => <div className="admin-report-row" key={item.id}><div><strong>{item.target_type} #{item.target_id}</strong><p>{item.reason}</p><small>{item.reporter} · {date(item.created_at)}</small></div><select value={item.status} onChange={(event) => updateReport(item.id, event.target.value)}><option value="pending">접수</option><option value="reviewed">검토 중</option><option value="resolved">처리 완료</option><option value="dismissed">반려</option></select></div>) : <p className="dashboard-empty">신고가 없습니다.</p>}</section>}</section>
}

function InquiryRow({ item, onSave }) { const [answer, setAnswer] = useState(item.answer || ''); const [status, setStatus] = useState(item.status); return <article className="admin-inquiry"><strong>{item.user_name || '회원'} · {date(item.created_at)}</strong><p>{item.content}</p><textarea rows="4" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="답변을 입력하세요." /><div><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="received">접수</option><option value="in_progress">처리 중</option><option value="answered">답변 완료</option><option value="closed">종료</option></select><button className="admin-button" onClick={() => onSave(item.id, answer, status)}>저장</button></div></article> }
