import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { apiFetch } from './api.js'
import { authStorage } from './authStorage.js'

const isNotice = (post) => post.category === '공지' || post.category === 'notice' || post.category === '공지사항'
export function PrivacyPolicy() { return <div className="container legal-page"><Link to="/" className="back">← 홈으로</Link><h1>개인정보처리방침</h1><p>시행일: 2026년 1월 1일</p><section><h2>개인정보의 수집</h2><p>서비스는 회원가입과 서비스 이용에 필요한 이름과 이메일을 수집합니다.</p></section><section><h2>이용 목적</h2><p>회원 식별, 서비스 제공, 게시글과 댓글 관리에 사용합니다.</p></section><section><h2>보관 및 파기</h2><p>회원 탈퇴 시 법령상 보관이 필요한 정보를 제외하고 파기합니다.</p></section></div> }
export function Terms() { return <div className="container legal-page"><Link to="/" className="back">← 홈으로</Link><h1>개인정보 이용약관</h1><p>시행일: 2026년 1월 1일</p><section><h2>서비스 이용</h2><p>회원은 타인의 권리를 침해하지 않는 범위에서 서비스를 이용해야 합니다.</p></section><section><h2>이용 제한</h2><p>불법 정보, 광고, 명예훼손 또는 운영 방해 게시물은 제한될 수 있습니다.</p></section></div> }
export function Inquiry({ loggedIn }) { const [content, setContent] = useState(''); const [message, setMessage] = useState(''); const submit = async (event) => { event.preventDefault(); if (!loggedIn) return setMessage('로그인 후 문의를 작성할 수 있습니다.'); try { await apiFetch('/inquiries', { method: 'POST', headers: { Authorization: 'Bearer ' + authStorage.getItem('token'), 'Content-Type': 'application/json' }, body: JSON.stringify({ content }) }); setContent(''); setMessage('문의가 접수되었습니다.'); } catch (error) { setMessage(error.message) } }; return <div className="container inquiry-page"><Link to="/" className="back">← 홈으로</Link><div className="title"><p className="eyebrow">SUPPORT</p><h1>1:1 문의</h1><p>서비스 이용 중 궁금한 점을 남겨주세요.</p></div><form className="editor" onSubmit={submit}><label>문의 내용<textarea required rows="8" value={content} onChange={(e) => setContent(e.target.value)} placeholder="문의 내용을 입력해 주세요." /></label>{message && <p className="profile-message">{message}</p>}<button className="button">문의하기</button></form></div> }
export function Notices({ posts }) { const notices = posts.filter(isNotice); return <div className="container notice-page"><Link to="/" className="back">← 홈으로</Link><div className="title"><p className="eyebrow">NOTICE</p><h1>공지사항</h1><p>서비스의 주요 안내와 업데이트를 확인하세요.</p></div><div className="notice-list">{notices.length ? notices.map((post) => <Link to={'/notices/' + post.id} className="notice-row" key={post.id}><div><strong>{post.title}</strong><small>{post.author || '관리자'} · {new Date(post.created_at).toLocaleDateString('ko-KR')}</small></div><span>›</span></Link>) : <p className="empty">등록된 공지사항이 없습니다.</p>}</div></div> }
export function NoticeDetail({ posts }) { const { id } = useParams(); const [remote, setRemote] = useState(null); const local = posts.find((post) => String(post.id) === id); const post = local || remote; useEffect(() => { if (!local) apiFetch('/posts/' + id).then(setRemote).catch(() => {}) }, [id, local]); if (!post) return <div className="container narrow"><p className="empty">공지사항을 불러오는 중입니다.</p></div>; if (!isNotice(post)) return <div className="container narrow"><p className="empty">공지사항을 찾을 수 없습니다.</p></div>; return <div className="container narrow notice-detail"><Link to="/notices" className="back">← 공지사항 목록</Link><article className="detail"><span className="category">공지사항</span><h1>{post.title}</h1><div className="meta">{post.author || '관리자'}<span>{new Date(post.created_at).toLocaleDateString('ko-KR')}</span></div><hr /><div className="content notice-content">{post.content}</div></article></div> }
